source 'https://github.com/CocoaPods/Specs.git'

target 'AHNavigationBar', :exclusive => true do
  pod "AHNavigationBar", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "AHNavigationBar", :path => "../"

  pod 'FBSnapshotTestCase'
end
